import { Caretaker } from "@/app/types/caretaker";

export const getExampleCaretaker = (): Caretaker[] => {
  return [
    {
      userId: "1",
      firstName: "Lena",
      lastName: "Mueller",
      phoneNumber: "+49 30 12345678",
      email: "lena.mueller23@email.com",
      profilePictureLink: "https://images.unsplash.com/photo-1600600423621-70c9f4416ae9?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      birthdate: "1985-06-15",
      numberKids: 2,
      maritalStatus: "Married",
      streetName: "Musterstr.",
      houseNumber: "12B",
      cityName: "Berlin",
      zip: "10115",
      country: "Germany",
      localityType: "Urban",
      space: 120,
      floor: 2,
      garden: false,
      residence: "Flat",
      tenure: "Rented",
      financialAssistance: true,
      employmentType: "Employed",
      previousAdoption: true,
      holidayCare: true,
      adoptionWillingness: true,
      experience: "No Experience",
      ctHours: [
        { weekday: "Monday", startTime: "08:00", endTime: "12:00" }
      ],
      score: 80
    },
    {
      userId: "2",
      firstName: "Max",
      lastName: "Weber",
      phoneNumber: "+49 30 12345678",
      email: "max.weber77@mailbox.com",
      profilePictureLink: "https://images.unsplash.com/photo-1508852951744-beab078a4b2b?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      birthdate: "1992-11-02",
      numberKids: 3,
      maritalStatus: "Single",
      streetName: "Hauptstr.",
      houseNumber: "45A",
      cityName: "Munich",
      zip: "80331",
      country: "Germany",
      localityType: "Urban",
      space: 250,
      floor: 1,
      garden: true,
      residence: "House",
      tenure: "Paid",
      financialAssistance: false,
      employmentType: "Freelancer",
      previousAdoption: false,
      holidayCare: false,
      adoptionWillingness: true,
      experience: "No Experience",
      ctHours: [
        { weekday: "Wednesday", startTime: "09:00", endTime: "13:00" }
      ],
      score: 100
    },
    {
      userId: "3",
      firstName: "Julian",
      lastName: "Schmidt",
      phoneNumber: "+49 30 12345678",
      email: "julian.schmidt@o2.pl",
      profilePictureLink: "https://images.unsplash.com/photo-1490138139357-fc819d02e344?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      birthdate: "1979-03-28",
      numberKids: 1,
      maritalStatus: "Married",
      streetName: "Landweg",
      houseNumber: "9C",
      cityName: "Hamburg",
      zip: "20257",
      country: "Germany",
      localityType: "Rural",
      space: 350,
      floor: 3,
      garden: true,
      residence: "House",
      tenure: "Paid",
      financialAssistance: true,
      employmentType: "Freelancer",
      previousAdoption: true,
      holidayCare: true,
      adoptionWillingness: false,
      experience: "No Experience",
      ctHours: [
        { weekday: "Friday", startTime: "08:30", endTime: "12:30" }
      ],
      score: 40
    },
    {
      userId: "4",
      firstName: "Felix",
      lastName: "Bauer",
      phoneNumber: "+49 30 12345678",
      email: "felix.bauer1985@webmail.com",
      profilePictureLink: "https://images.unsplash.com/photo-1500629723675-4d6b0685936a?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      birthdate: "1990-08-20",
      numberKids: 4,
      maritalStatus: "Single",
      streetName: "Bergstr.",
      houseNumber: "22A",
      cityName: "Frankfurt",
      zip: "60311",
      country: "Germany",
      localityType: "Urban",
      space: 180,
      floor: 5,
      garden: false,
      residence: "Flat",
      tenure: "Rented",
      financialAssistance: false,
      employmentType: "Employed",
      previousAdoption: false,
      holidayCare: true,
      adoptionWillingness: true,
      experience: "No Experience",
      ctHours: [
        { weekday: "Tuesday", startTime: "13:00", endTime: "17:00" }
      ],
      score: 20
    }
  ];
};
