services:
  db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

  adminer:
    image: adminer:5
    restart: always
    ports:
      - 3400:8080
    environment:
      TOKEN_SECRET: ${TOKEN_SECRET}
