export const birdBreeds = [
  "African Grey Parrot",
  "Amazon Parrot",
  "Budgerigar",
  "Canary",
  "Cockatiel",
  "Cockatoo",
  "Conure",
  "Dove",
  "Eclectus Parrot",
  "Finch",
  "Indian Ringneck Parakeet",
  "Lovebird",
  "Macaw",
  "Mynah",
  "Parakeet",
  "Parrotlet",
  "Pigeon",
  "Quaker Parrot",
  "Rosella",
  "Senegal Parrot",
  "Society Finch",
  "Zebra Finch",
];
