export const rodentBreeds = [
  "Syrian Hamster",
  "Dwarf Campbell Russian Hamster",
  "Dwarf Winter White Russian Hamster",
  "Roborovski Hamster",
  "Chinese Hamster",
  "Guinea Pig",
  "Abyssinian Guinea Pig",
  "Peruvian Guinea Pig",
  "Silkie Guinea Pig",
  "Teddy Guinea Pig",
  "American Guinea Pig",
  "Rex Guinea Pig",
  "Mouse",
  "Fancy Mouse",
  "Rat",
  "Fancy Rat",
  "Dumbo Rat",
  "Gerbil",
  "Mongolian Gerbil",
  "Chinchilla",
  "Degus",
  "Capybara",
  "Prairie Dog",
];
